apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
     app: nginx-app
spec:
  type: LoadBalancer
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
  selector:
    app: nginx-app